/**
 * Domain representation of a site — a named collection of pages that each
 * point to a generated artifact.
 *
 * ISO 8601 strings (not Date objects) for timestamps — serializes cleanly
 * across the API boundary and Postgres returns them as strings by default.
 */
export interface SiteRecord {
  /** "site-" + 12 lowercase hex chars, generated by crypto.randomBytes(6). */
  id: string;
  name: string;
  createdAt: string; // ISO 8601
  updatedAt: string; // ISO 8601
}

/**
 * A single page within a site. Each page maps a URL slug to a generated
 * artifact and carries display metadata.
 */
export interface SitePage {
  siteId: string;
  /** URL-safe slug, e.g. "/" or "/about". */
  slug: string;
  /** Human-readable display title, e.g. "Home" or "About". */
  title: string;
  /** The artifact rendered at this slug. */
  artifactId: string;
  /** Sort order. listPages returns pages ascending by this field. */
  position: number;
  createdAt: string; // ISO 8601
}

/**
 * Contract for storing and querying site + page metadata. Two
 * non-Supabase implementations live alongside this file:
 *  - MemorySiteStore (in-process, tests + dev fallback)
 *  - FsSiteStore (filesystem-backed, persists across restarts)
 *
 * A third implementation (SupabaseSiteStore) and the runtime factory that
 * selects between them will be added in Task 3.
 *
 * Error semantics:
 *  - addPage throws an Error with "SLUG_EXISTS" in the message if the slug
 *    already exists for that site.
 *  - addPage throws an Error with "SITE_NOT_FOUND" if siteId is unknown.
 *  - setPageArtifact returns null for unknown site or slug (does not throw).
 *  - removePage returns false for unknown site or slug (does not throw).
 */
export interface SiteStore {
  /** Creates a new site and returns the persisted record. */
  createSite(input: { name: string }): Promise<SiteRecord>;

  /** Returns the site with the given id, or null if not found. */
  getSite(id: string): Promise<SiteRecord | null>;

  /**
   * Adds a page to the site. Throws if siteId is unknown (SITE_NOT_FOUND) or
   * if the slug already exists in that site (SLUG_EXISTS).
   */
  addPage(
    siteId: string,
    input: { slug: string; title: string; artifactId: string; position: number },
  ): Promise<SitePage>;

  /**
   * Removes the page identified by siteId + slug. Returns true if the page
   * was found and removed, false if not found (unknown site or slug).
   */
  removePage(siteId: string, slug: string): Promise<boolean>;

  /**
   * Updates the artifactId for the given slug. Returns the updated page, or
   * null if the site or slug is not found.
   */
  setPageArtifact(siteId: string, slug: string, artifactId: string): Promise<SitePage | null>;

  /** Returns all pages for the site, ordered by position ascending. Returns [] if the site does not exist. */
  listPages(siteId: string): Promise<SitePage[]>;
}
