/**
 * Shared artifact-id shape validator.
 *
 * Valid ids are either:
 *   - Filesystem timestamp ids:  `20260602-160516-468c`  (generated by timestampId())
 *   - Supabase UUIDs:            `a1b2c3d4-e5f6-...`     (crypto.randomUUID())
 *
 * Both forms contain only `[A-Za-z0-9-]` and are well under 64 chars.
 * Slashes, dots, percent-signs, and other path-relevant chars are NOT in the
 * allowed set — so a traversal attempt like `../../etc/passwd` or its
 * URL-encoded equivalent is rejected before it reaches the archive store.
 *
 * Mirror of `isValidToken` in `src/lib/shares/token.ts`.
 */
const ARTIFACT_ID_REGEX = /^[A-Za-z0-9-]+$/;
const ARTIFACT_ID_MAX_LENGTH = 64;

/**
 * Type guard: true iff `s` is a string that matches the canonical artifact-id
 * shape. Called by route handlers before any store lookup — malformed ids are
 * treated as not-found (404) rather than forwarded to the fs layer.
 */
export function isValidArtifactId(s: unknown): s is string {
  return (
    typeof s === 'string' &&
    s.length > 0 &&
    s.length <= ARTIFACT_ID_MAX_LENGTH &&
    ARTIFACT_ID_REGEX.test(s)
  );
}
